import type { QueueItem, Submission, RejectionReason, AgentTrustScore, QAReportOverview, Outlet, OutletBaseline, User } from '../types';

export const MOCK_USERS: Record<string, User> = {
  admin: { id: 'usr-1', name: 'QA Reviewer / Admin', email: 'admin@metrix.qa', role: 'admin' },
  reviewer: { id: 'usr-1', name: 'QA Reviewer / Admin', email: 'admin@metrix.qa', role: 'admin' },
};

// applies_to_quest_types must use the real App\Enums\QuestType values
// ('quest', 'verification', 'survey') — this used to list mock-only
// placeholder strings that no real quest_type ever matched, which silently
// emptied ReasonCodeSelect's dropdown for every real submission (see
// backend/database/seeders/RejectionReasonSeeder.php for the full story).
export const MOCK_REJECTION_REASONS: RejectionReason[] = [
  { code: 'REUSED_PHOTO', label: 'Possible Reused/Duplicate Photo', applies_to_quest_types: ['quest', 'verification', 'survey'] },
  { code: 'OUT_OF_GEOFENCE', label: 'Submission Outside Geofence Radius', applies_to_quest_types: ['quest', 'verification', 'survey'] },
  { code: 'PRICE_OUTLIER', label: 'Unusual Price Entry / Typo', applies_to_quest_types: ['quest'] },
  { code: 'BLURRY_PHOTO', label: 'Photo Unclear or Obstructed', applies_to_quest_types: ['quest', 'verification', 'survey'] },
  { code: 'TIMESTAMP_MISMATCH', label: 'Survey Completed Too Quickly / Timestamp Anomaly', applies_to_quest_types: ['quest', 'verification', 'survey'] },
  { code: 'WRONG_OUTLET_SPOT', label: 'Photo Baseline Similarity Failure (Wrong Spot)', applies_to_quest_types: ['quest', 'verification', 'survey'] },
  { code: 'INCOMPLETE_ANSWERS', label: 'Missing Required Fields or Invalid Input', applies_to_quest_types: ['quest', 'verification', 'survey'] },
];

export const MOCK_QUEUE_ITEMS: QueueItem[] = [
  {
    id: 'a41f9e2c-88b1-4e3a-9c2d-7f001a3b55e0',
    quest: { id: 'QST-OIL-SHOA-001', title: 'Edible Oils Facing & Price Audit', form_code: 'QST-OIL-SHOA-001_v3', quest_type: 'price_check' },
    outlet: { id: 'OUT-SHOA-BOLE-014', name: 'Shoa Supermarket', branch: 'Bole Atlas (014)', city: 'Addis Ababa' },
    agent_id: 'AGT-10432',
    submitted_at: '2026-07-21T09:18:53+03:00',
    status: 'pending',
    flags: [
      { rule_name: 'price_range_outlier', result: 'flag', severity: 'medium', detail: '3L Tena Oil 1,180 ETB price verified against market range' },
      { rule_name: 'geofence_check', result: 'pass', severity: 'low', detail: 'Agent location 6m within outlet radius' },
    ],
    payout_amount: 350,
    payment_status: 'pending',
    trust_score: {
      total_score: 92,
      gps_score: 98,
      gps_details: {
        shop_actual_gps: { lat: 8.98721, lng: 38.78962 },
        submission_gps: { lat: 8.98721, lng: 38.78962, accuracy_m: 6 },
        photo_gps: { lat: 8.98720, lng: 38.78960 },
        distance_to_shop_m: 2.1,
        photo_distance_to_shop_m: 2.5,
      },
      time_score: 95,
      time_details: { duration_seconds: 285, expected_seconds: 240, passed: true },
      photo_score: 89,
      photo_details: { clarity_pass: true, baseline_similarity: 0.89 },
      answer_score: 100,
      answer_details: { valid_answers_count: 12, total_answers_count: 12 },
      price_score: 85,
      price_details: { outliers_count: 1, total_prices_count: 2 },
      completeness_score: 100,
      completeness_details: { completed_fields: 12, required_fields: 12 },
      weights: { gps: 0.20, time: 0.15, photo: 0.20, answer: 0.15, price: 0.20, completeness: 0.10 },
    },
  },
  {
    id: 'sub-102',
    quest: { id: 'QST-DAIRY-002', title: 'Dairy & Beverages Price Audit', form_code: 'PRICE-DAIRY-01', quest_type: 'price_check' },
    outlet: { id: 'OUT-NOVIS-KAZ-002', name: 'Novis Supermarket', branch: 'Kazanchis', city: 'Addis Ababa' },
    agent_id: 'AGT-11840',
    submitted_at: new Date(Date.now() - 42 * 60000).toISOString(),
    status: 'pending',
    flags: [
      { rule_name: 'price_range_outlier', result: 'flag', severity: 'medium', detail: 'SKU price 450 ETB is +120% vs 200 ETB historical avg' },
    ],
    payout_amount: 280,
    payment_status: 'pending',
    trust_score: {
      total_score: 78,
      gps_score: 95,
      gps_details: {
        shop_actual_gps: { lat: 9.0182, lng: 38.7635 },
        submission_gps: { lat: 9.0183, lng: 38.7636, accuracy_m: 12 },
        photo_gps: { lat: 9.0183, lng: 38.7636 },
        distance_to_shop_m: 14.2,
        photo_distance_to_shop_m: 14.2,
      },
      time_score: 85,
      time_details: { duration_seconds: 190, expected_seconds: 240, passed: true },
      photo_score: 75,
      photo_details: { clarity_pass: true, baseline_similarity: 0.75 },
      answer_score: 90,
      answer_details: { valid_answers_count: 9, total_answers_count: 10 },
      price_score: 55,
      price_details: { outliers_count: 1, total_prices_count: 2 },
      completeness_score: 90,
      completeness_details: { completed_fields: 9, required_fields: 10 },
      weights: { gps: 0.20, time: 0.15, photo: 0.20, answer: 0.15, price: 0.20, completeness: 0.10 },
    },
  },
  {
    id: 'sub-103',
    quest: { id: 'QST-COFFEE-009', title: 'Coffee Baseline Photo Verification', form_code: 'AGRI-COFFEE-09', quest_type: 'agri_verify' },
    outlet: { id: 'OUT-[#3]-SARBET', name: 'Kaldis Central Hub', branch: 'Sarbet', city: 'Addis Ababa' },
    agent_id: 'AGT-89102',
    submitted_at: new Date(Date.now() - 110 * 60000).toISOString(),
    status: 'pending',
    flags: [
      { rule_name: 'possible_wrong_location', result: 'flag', severity: 'medium', detail: 'Embedding similarity 0.42 is below 0.60 spot baseline' },
      { rule_name: 'timestamp_consistency', result: 'flag', severity: 'medium', detail: 'Form completed in 42 seconds (expected >120s)' },
    ],
    payout_amount: 450,
    payment_status: 'under_review',
    trust_score: {
      total_score: 48,
      gps_score: 40,
      gps_details: {
        shop_actual_gps: { lat: 8.9880, lng: 38.7420 },
        submission_gps: { lat: 8.9912, lng: 38.7450, accuracy_m: 35 },
        photo_gps: { lat: 8.9915, lng: 38.7452 },
        distance_to_shop_m: 480,
        photo_distance_to_shop_m: 510,
      },
      time_score: 30,
      time_details: { duration_seconds: 42, expected_seconds: 180, passed: false },
      photo_score: 42,
      photo_details: { clarity_pass: false, baseline_similarity: 0.42 },
      answer_score: 70,
      answer_details: { valid_answers_count: 7, total_answers_count: 10 },
      price_score: 100,
      price_details: { outliers_count: 0, total_prices_count: 0 },
      completeness_score: 70,
      completeness_details: { completed_fields: 7, required_fields: 10 },
      weights: { gps: 0.35, time: 0.10, photo: 0.25, answer: 0.15, price: 0.0, completeness: 0.15 },
    },
  },
];

export const MOCK_SUBMISSIONS_MAP: Record<string, Submission> = {
  'a41f9e2c-88b1-4e3a-9c2d-7f001a3b55e0': {
    id: 'a41f9e2c-88b1-4e3a-9c2d-7f001a3b55e0',
    submission_id: 'a41f9e2c-88b1-4e3a-9c2d-7f001a3b55e0',
    quest_id: 'QST-OIL-SHOA-001',
    quest: { id: 'QST-OIL-SHOA-001', title: 'Edible Oils Facing & Price Audit', form_code: 'QST-OIL-SHOA-001_v3', quest_type: 'price_check' },
    outlet_id: 'OUT-SHOA-BOLE-014',
    outlet: { id: 'OUT-SHOA-BOLE-014', name: 'Shoa Supermarket', branch: 'Bole Atlas (014)', city: 'Addis Ababa', approved_radius_m: 50, geofence_radius_m: 150, gps_lat: 8.98721, gps_lng: 38.78962 },
    agent_id: 'AGT-10432',
    config_version: 'QST-OIL-SHOA-001_v3',
    survey_start_at: '2026-07-21T09:14:02+03:00',
    survey_end_at: '2026-07-21T09:18:47+03:00',
    submitted_at: '2026-07-21T09:18:53+03:00',
    timestamps: {
      survey_start_at: '2026-07-21T09:14:02+03:00',
      survey_end_at: '2026-07-21T09:18:47+03:00',
      submitted_at: '2026-07-21T09:18:53+03:00',
    },
    gps: { lat: 8.98721, lng: 38.78962, accuracy_m: 6 },
    status: 'pending',
    payout_amount: 350,
    payment_status: 'pending',
    trust_score: {
      total_score: 92,
      gps_score: 98,
      gps_details: {
        shop_actual_gps: { lat: 8.98721, lng: 38.78962 },
        submission_gps: { lat: 8.98721, lng: 38.78962, accuracy_m: 6 },
        photo_gps: { lat: 8.98720, lng: 38.78960 },
        distance_to_shop_m: 2.1,
        photo_distance_to_shop_m: 2.5,
      },
      time_score: 95,
      time_details: { duration_seconds: 285, expected_seconds: 240, passed: true },
      photo_score: 89,
      photo_details: { clarity_pass: true, baseline_similarity: 0.89 },
      answer_score: 100,
      answer_details: { valid_answers_count: 12, total_answers_count: 12 },
      price_score: 85,
      price_details: { outliers_count: 1, total_prices_count: 2 },
      completeness_score: 100,
      completeness_details: { completed_fields: 12, required_fields: 12 },
      weights: { gps: 0.20, time: 0.15, photo: 0.20, answer: 0.15, price: 0.20, completeness: 0.10 },
    },
    client_app_version: '2.4.1',
    answers: [
      { question_id: 'q1_branch_select', input_type: 'dropdown', value: 'OUT-SHOA-BOLE-014' },
      { question_id: 'q2_confirm_branch', input_type: 'single_choice', value: 'Yes' },
      { question_id: 'q3_available', input_type: 'single_choice', value: 'Yes' },
      {
        question_id: 'q4_pack_sizes',
        input_type: 'repeat_table',
        value: [
          { row_id: 'row_1', pack_size: '1L', available: true },
          { row_id: 'row_2', pack_size: '3L', available: true },
          { row_id: 'row_3', pack_size: '5L', available: false },
        ],
      },
      { question_id: 'q5_price', input_type: 'numeric_price', row_id: 'row_1', value: 410, currency: 'ETB' },
      { question_id: 'q5_price', input_type: 'numeric_price', row_id: 'row_2', value: 1180, currency: 'ETB' },
      { question_id: 'q6_price_photo', input_type: 'photo', row_id: 'row_1', media_ref: 'media_001' },
      { question_id: 'q6_price_photo', input_type: 'photo', row_id: 'row_2', media_ref: 'media_002' },
      { question_id: 'q7_shelf_photo', input_type: 'photo', media_ref: 'media_003' },
      { question_id: 'q8_competitors', input_type: 'multiple_choice', value: ['Aveka'] },
      { question_id: 'q9_note', input_type: 'text', value: '' },
      { question_id: 'q10_confirm', input_type: 'checkbox', value: true },
    ],
    media: [
      {
        media_ref: 'media_001',
        question_id: 'q6_price_photo',
        row_id: 'row_1',
        media_type: 'image',
        file_ref: 's3://metrix-media/2026/07/media_001.jpg',
        url: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?auto=format&fit=crop&w=800&q=80',
        captured_at: '2026-07-21T09:16:10+03:00',
        gps_at_capture: { lat: 8.98720, lng: 38.78960 },
        baseline: {
          photo_url: 'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=800&q=80',
          spot_label: 'Edible Oils Shelf Aisle 1',
          hash_distance: 12,
          embedding_similarity: 0.89,
          similarity_method: 'open_clip_vit_b_32',
          gps_distance_m: 2.1,
        },
      },
      {
        media_ref: 'media_002',
        question_id: 'q6_price_photo',
        row_id: 'row_2',
        media_type: 'image',
        file_ref: 's3://metrix-media/2026/07/media_002.jpg',
        url: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80',
        captured_at: '2026-07-21T09:16:41+03:00',
        gps_at_capture: { lat: 8.98721, lng: 38.78961 },
      },
      {
        media_ref: 'media_003',
        question_id: 'q7_shelf_photo',
        media_type: 'image',
        file_ref: 's3://metrix-media/2026/07/media_003.jpg',
        url: 'https://images.unsplash.com/photo-1583258292688-d0213dc5a3a8?auto=format&fit=crop&w=800&q=80',
        captured_at: '2026-07-21T09:17:55+03:00',
        gps_at_capture: { lat: 8.98721, lng: 38.78962 },
      },
    ],
    prices: [
      { question_id: 'q5_price', sku_id: 'SKU-TENA-OIL-1L', row_id: 'row_1', value: 410, currency: 'ETB', unit: 'per bottle' },
      { question_id: 'q5_price', sku_id: 'SKU-TENA-OIL-3L', row_id: 'row_2', value: 1180, currency: 'ETB', unit: 'per bottle' },
    ],
    flags: [
      { rule_name: 'price_range_outlier', result: 'flag', severity: 'medium', detail: '3L Tena Oil 1,180 ETB price verified against market range' },
      { rule_name: 'geofence_check', result: 'pass', severity: 'low', detail: 'Agent location 6m within outlet radius' },
    ],
    review_history: [],
  },
};

// Aliasing sub-101 to the new payload
MOCK_SUBMISSIONS_MAP['sub-101'] = MOCK_SUBMISSIONS_MAP['a41f9e2c-88b1-4e3a-9c2d-7f001a3b55e0'];

export const MOCK_OUTLETS: Outlet[] = [
  { id: 'OUT-SHOA-BOLE-014', name: 'Shoa Supermarket', chain: 'Shoa Retail', branch: 'Bole Atlas (014)', city: 'Addis Ababa', gps_lat: 8.98721, gps_lng: 38.78962 },
  { id: 'out-2', name: 'Novis Supermarket', chain: 'Novis Group', branch: 'Kazanchis', city: 'Addis Ababa', gps_lat: 9.0182, gps_lng: 38.7635 },
  { id: 'out-3', name: 'Kaldis Central Hub', chain: 'Kaldis Coffee', branch: 'Sarbet', city: 'Addis Ababa', gps_lat: 8.9880, gps_lng: 38.7420 },
];

export const MOCK_BASELINES_MAP: Record<string, OutletBaseline[]> = {
  'OUT-SHOA-BOLE-014': [
    {
      id: 'base-101',
      spot_label: 'Edible Oils Shelf Aisle 1',
      baseline_gps_lat: 8.98721,
      baseline_gps_lng: 38.78962,
      baseline_gps_radius_m: 25,
      photo_url: 'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=800&q=80',
      captured_by: 'Supervisor Samuel (Field Ops)',
      captured_at: '2026-06-15T09:30:00Z',
      notes: 'Edible oil display section.',
    },
  ],
};

export const MOCK_TRUST_SCORES: Record<string, AgentTrustScore> = {
  'AGT-10432': {
    agent_id: 'AGT-10432',
    approval_rate: 96.5,
    backcheck_pass_rate: 99.0,
    tier: 'Gold',
    overall_trust_score: 92,
    rejection_breakdown: [
      { reason_code: 'BLURRY_PHOTO', label: 'Blurry Photo', count: 1 },
    ],
    recent_builds: [
      {
        submission_id: 'a41f9e2c-88b1-4e3a-9c2d-7f001a3b55e0',
        quest_title: 'Edible Oils Facing & Price Audit',
        date: '2026-07-21 09:18',
        trust_score: 92,
        gps_score: 98,
        time_score: 95,
        photo_score: 89,
        completeness_score: 100,
        audit_confirmation_score: 100,
        outcome: 'approved',
      },
      {
        submission_id: 'sub-098',
        quest_title: 'Beverage Inventory Count',
        date: '2026-07-20 14:22',
        trust_score: 95,
        gps_score: 100,
        time_score: 92,
        photo_score: 94,
        completeness_score: 100,
        audit_confirmation_score: 100,
        outcome: 'approved',
      },
      {
        submission_id: 'sub-085',
        quest_title: 'Supermarket Dairy Audit',
        date: '2026-07-18 11:05',
        trust_score: 88,
        gps_score: 92,
        time_score: 88,
        photo_score: 82,
        completeness_score: 95,
        audit_confirmation_score: 100,
        outcome: 'approved',
      },
    ],
  },
  'AGT-11840': {
    agent_id: 'AGT-11840',
    approval_rate: 88.0,
    backcheck_pass_rate: 92.0,
    tier: 'Silver',
    overall_trust_score: 78,
    rejection_breakdown: [
      { reason_code: 'PRICE_OUTLIER', label: 'Price Outlier', count: 2 },
      { reason_code: 'BLURRY_PHOTO', label: 'Blurry Photo', count: 1 },
    ],
    recent_builds: [
      {
        submission_id: 'sub-102',
        quest_title: 'Dairy & Beverages Price Audit',
        date: '2026-07-22 19:55',
        trust_score: 78,
        gps_score: 95,
        time_score: 85,
        photo_score: 75,
        completeness_score: 90,
        audit_confirmation_score: 75,
        outcome: 'pending',
      },
      {
        submission_id: 'sub-072',
        quest_title: 'Personal Care Price Check',
        date: '2026-07-15 16:40',
        trust_score: 81,
        gps_score: 90,
        time_score: 80,
        photo_score: 85,
        completeness_score: 90,
        audit_confirmation_score: 100,
        outcome: 'approved',
      },
    ],
  },
  'AGT-89102': {
    agent_id: 'AGT-89102',
    approval_rate: 62.4,
    backcheck_pass_rate: 70.0,
    tier: 'Flagged',
    overall_trust_score: 48,
    rejection_breakdown: [
      { reason_code: 'OUT_OF_GEOFENCE', label: 'Outside Geofence', count: 5 },
      { reason_code: 'WRONG_OUTLET_SPOT', label: 'Wrong Baseline Spot', count: 4 },
      { reason_code: 'TIMESTAMP_MISMATCH', label: 'Too Fast Survey', count: 3 },
    ],
    recent_builds: [
      {
        submission_id: 'sub-103',
        quest_title: 'Coffee Baseline Photo Verification',
        date: '2026-07-22 18:45',
        trust_score: 48,
        gps_score: 40,
        time_score: 30,
        photo_score: 42,
        completeness_score: 70,
        audit_confirmation_score: 75,
        outcome: 'pending',
      },
      {
        submission_id: 'sub-060',
        quest_title: 'Spices & Grains Check',
        date: '2026-07-12 10:15',
        trust_score: 52,
        gps_score: 45,
        time_score: 40,
        photo_score: 50,
        completeness_score: 75,
        audit_confirmation_score: 35,
        outcome: 'rejected',
      },
    ],
  },
};

export const MOCK_REPORT_OVERVIEW: QAReportOverview = {
  queue_depth: 42,
  queue_by_status: { pending_review: 30, backcheck: 8, sent_back: 4 },
  oldest_pending_age_hours: 36.2,
  avg_time_in_queue_minutes: 28.5,
  avg_trust_score: 88.4,
  approval_rate: 90.6,
  rejection_rate: 9.4,
  backcheck_rate: 7.1,
  trust_tier_distribution: [
    { tier: 'Gold', count: 18 },
    { tier: 'Silver', count: 24 },
    { tier: 'Bronze', count: 11 },
    { tier: 'Flagged', count: 3 },
  ],
  approval_rate_by_quest: [
    { quest_title: 'Edible Oils Facing', approval_rate: 95.0, total: 240 },
    { quest_title: 'FMCG Shelf Check', approval_rate: 92.4, total: 420 },
    { quest_title: 'Dairy Price Audit', approval_rate: 84.6, total: 310 },
  ],
  approval_rate_by_city: [
    { city: 'Addis Ababa', approval_rate: 88.5, total: 650 },
    { city: 'Hawassa', approval_rate: 91.2, total: 210 },
  ],
  reviewer_throughput: [
    { reviewer_name: 'QA Reviewer / Admin', reviewed_count: 210, avg_decision_time_minutes: 1.8 },
  ],
  top_qa_flags: [
    { rule_name: 'no_outlet_baseline_configured', result: 'flag', severity: 'low', count: 14 },
    { rule_name: 'baseline_photo_mismatch', result: 'flag', severity: 'high', count: 9 },
    { rule_name: 'low_photo_resolution', result: 'fail', severity: 'high', count: 6 },
  ],
  rejection_breakdown: [
    { reason_code: 'PRICE_OUTLIER', label: 'Price Outlier', count: 7 },
    { reason_code: 'PHOTO_MISMATCH', label: 'Photo Baseline Mismatch', count: 4 },
  ],
  payment_funnel: [
    { wallet_state: 'paid', currency: 'ETB', count: 210, total_amount: 42000 },
    { wallet_state: 'pending', currency: 'ETB', count: 30, total_amount: 6000 },
    { wallet_state: 'rejected', currency: 'ETB', count: 22, total_amount: 0 },
  ],
};
